// src/lib/components/ui/Button.svelte
<script lang="ts">
	import { cva, cx } from '$lib/cva';
	import type { VariantProps } from 'cva';
	import type { Snippet } from 'svelte';
	import type { HTMLButtonAttributes } from 'svelte/elements';

	const button = cva({
		base: 'inline-flex items-center justify-center gap-2 rounded-full px-8 py-4 text-base font-medium transition-all focus-visible:outline-2 focus-visible:outline-offset-2 active:scale-[0.97] disabled:pointer-events-none disabled:opacity-50',
		variants: {
			variant: {
				primary:
					'bg-neutral-900 text-white hover:bg-neutral-800 focus-visible:outline-neutral-900 dark:bg-neutral-100 dark:text-neutral-900 dark:hover:bg-neutral-200 dark:focus-visible:outline-neutral-100'
			}
		},
		defaultVariants: {
			variant: 'primary'
		}
	});

	type ButtonVariants = VariantProps<typeof button>;

	interface Props extends HTMLButtonAttributes {
		variant?: ButtonVariants['variant'];
		loading?: boolean;
		children: Snippet;
	}

	let { variant = 'primary', loading = false, disabled, class: className, children, ...rest }: Props = $props();
</script>

<button
	class={cx(button({ variant }), className)}
	disabled={disabled || loading}
	{...rest}
>
	{#if loading}
		<span class="icon-[lucide--loader-2] animate-spin size-4"></span>
	{/if}
	{@render children()}
</button>

// lib/ui/button.tsx
"use client";

import { Button as BaseButton } from "@base-ui/react/button";
import { cva, type VariantProps } from "class-variance-authority";
import { Loader2 } from "lucide-react";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { cn } from "@/lib/utils/cn";

export const buttonVariants = cva(
  "inline-flex items-center justify-center gap-1 font-medium text-sm transition-colors duration-150 cursor-pointer focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-500 disabled:cursor-not-allowed",
  {
    variants: {
      variant: {
        primary:
          "bg-violet-500 text-white hover:bg-violet-600 active:bg-violet-700 disabled:bg-foreground/10 disabled:text-foreground/40 rounded-full",
        secondary:
          "bg-foreground/10 text-foreground hover:bg-foreground/15 active:bg-foreground/20 disabled:bg-foreground/5 disabled:text-foreground/40 rounded-full",
        ghost:
          "bg-transparent text-foreground/70 hover:bg-foreground/10 active:bg-foreground/15 disabled:text-foreground/40 disabled:hover:bg-transparent rounded-full",
        danger:
          "bg-red-500 text-white hover:bg-red-600 active:bg-red-700 disabled:bg-foreground/10 disabled:text-foreground/40 rounded-full",
        link: "bg-transparent text-foreground/50 hover:text-foreground/80 disabled:text-foreground/40 p-0",
        "link-primary":
          "bg-transparent text-violet-500 hover:text-violet-600 dark:hover:text-violet-400 disabled:text-foreground/40 p-0",
      },
      size: {
        default: "px-6 py-3",
        sm: "px-4 py-2 text-xs",
        lg: "px-8 py-4 text-base",
      },
    },
    compoundVariants: [
      {
        variant: ["link", "link-primary"],
        className: "px-0 py-0",
      },
    ],
    defaultVariants: {
      variant: "primary",
      size: "default",
    },
  },
);

type ButtonProps = ComponentPropsWithoutRef<typeof BaseButton> &
  VariantProps<typeof buttonVariants> & {
    loading?: boolean;
    children: ReactNode;
  };

export function Button({
  variant,
  size,
  loading = false,
  disabled,
  className,
  children,
  render,
  ...props
}: ButtonProps) {
  const isDisabled = disabled || loading;

  return (
    <BaseButton
      disabled={isDisabled}
      focusableWhenDisabled={loading}
      className={cn(buttonVariants({ variant, size }), className)}
      render={render}
      nativeButton={render === undefined}
      {...props}
    >
      {loading && (
        <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
      )}
      {children}
    </BaseButton>
  );
}
