// references/legacy-app/app/(main)/search/_components/search-input.tsx
"use client";

import { Search, X } from "lucide-react";
import { useTranslations } from "next-intl";
import { Input } from "@/lib/ui/input";

interface SearchInputProps {
  value: string;
  onChange: (value: string) => void;
  onClear: () => void;
  isPending: boolean;
}

export function SearchInput({
  value,
  onChange,
  onClear,
  isPending,
}: SearchInputProps) {
  const t = useTranslations("search");

  return (
    <div className="relative">
      <Search
        className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-muted"
        aria-hidden="true"
      />
      <Input
        type="text"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={t("placeholder")}
        aria-label={t("aria_label")}
        className="pl-12 pr-12"
        autoComplete="off"
        autoFocus
      />
      {value && (
        <button
          type="button"
          onClick={onClear}
          className="absolute right-4 top-1/2 -translate-y-1/2 rounded-full p-1 text-muted transition-colors hover:bg-accent-soft hover:text-foreground"
          aria-label={t("clear")}
        >
          <X className="h-4 w-4" />
        </button>
      )}
      {isPending && (
        <div className="absolute right-12 top-1/2 -translate-y-1/2">
          <div className="h-4 w-4 animate-spin rounded-full border-2 border-accent border-t-transparent" />
        </div>
      )}
    </div>
  );
}

// src/lib/components/ui/search-input.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from 'svelte/elements';
	import { Search, X } from 'lucide-svelte';

	interface Props extends HTMLInputAttributes {
		value?: string;
	}

	let { class: className, value = $bindable(''), ...rest }: Props = $props();

	const baseClasses =
		'block w-full rounded-lg h-10 pl-9 pr-9 text-sm bg-white text-neutral-900 border border-neutral-300 dark:bg-neutral-900 dark:text-neutral-50 dark:border-neutral-700 placeholder:text-neutral-400 dark:placeholder:text-neutral-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-neutral-950 dark:focus-visible:outline-neutral-50 disabled:pointer-events-none disabled:opacity-50';
</script>

<div class={['relative', className]}>
	<Search
		size={16}
		class="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-neutral-400 dark:text-neutral-500"
	/>
	<input type="text" bind:value class={baseClasses} {...rest} />
	{#if value}
		<button
			type="button"
			class="absolute right-1.5 top-1/2 -translate-y-1/2 inline-flex h-7 w-7 items-center justify-center rounded-full text-neutral-400 transition-colors hover:bg-neutral-100 hover:text-neutral-600 dark:text-neutral-500 dark:hover:bg-neutral-800 dark:hover:text-neutral-300"
			onclick={() => (value = '')}
			aria-label="Clear search"
		>
			<X size={16} />
		</button>
	{/if}
</div>
