// src/lib/components/ui/FormField.svelte
<script lang="ts">
	import { cx } from '$lib/cva';
	import type { Snippet } from 'svelte';

	interface Props {
		label?: string;
		error?: string;
		class?: string;
		children: Snippet;
	}

	let { label, error, class: className, children }: Props = $props();
</script>

<div class={cx('space-y-0', className)}>
	{#if label}
		<label class="block">
			<span class="mb-1.5 block text-sm font-medium text-neutral-700 dark:text-neutral-300">{label}</span>
			{@render children()}
		</label>
	{:else}
		{@render children()}
	{/if}
	{#if error}
		<p class="mt-1.5 text-sm text-red-500 dark:text-red-400">{error}</p>
	{/if}
</div>

// app/(main)/settings/create-business/_components/form-field.tsx
"use client";

import type { ReactNode } from "react";
import { cn } from "@/lib/utils/cn";

interface FormFieldProps {
  label: string;
  error?: string;
  hint?: string;
  required?: boolean;
  children: ReactNode;
  className?: string;
}

export function FormField({
  label,
  error,
  hint,
  required,
  children,
  className,
}: FormFieldProps) {
  return (
    <div className={cn("space-y-2", className)}>
      <label className="block text-sm font-medium text-foreground">
        {label}
        {required && <span className="ml-1 text-red-500">*</span>}
      </label>
      {children}
      {hint && !error && (
        <p className="text-xs text-foreground/50">{hint}</p>
      )}
      {error && <p className="text-xs text-red-500">{error}</p>}
    </div>
  );
}
